### ISSUE TITLE
WordDataBase reference uses 2nd coroutine argument prematurely

### ISSUE THREAD

**Issue by galaxi76** [googlecodelabs/android-room-with-a-view#127]
Step 10 Create the ViewModel has an init block that creates a reference to the WordDataBase by passing in context and a CoroutineScope as parameters, but the CoroutineScope argument is only added to the getDatabase() method of WordRoomDatabase only in step 13

**Comment by MikesGitHome** [comment]
Second on this, I'm still super new to Kotlin/Android Studio so I'm not sure whether to delete the CoroutineScope or what...

**Comment by b1sar** [comment]
Came here to report the same issue. As @galaxi76 point it out correctly, in step 10, there is this line
`val wordsDao = WordRoomDatabase.getDatabase(application, viewModelScope).wordDao()`
which accepts a CoroutineScope, but that parameter hasn't been added to the `getDatabase` method  in the previous steps.

The line should be as follows(I think):
`val wordsDao = WordRoomDatabase.getDatabase(application).wordDao()`
then, and only then the Step 10 will be built without errors. Otherwise, users will have to wait until step 13 for their code to run correctly but that disrupts the flow of the code lab.

**Comment by florina-muntenescu** [comment]
Codelab updated. 
Thanks all for reporting
