### ISSUE TITLE
Step 9 - Create the ViewModel: Duplicate word in comment

### ISSUE THREAD

**Issue by edwinderepuesto** [googlecodelabs/android-room-with-a-view#87]
There's a duplicate word ("the") in a code comment in the "Implement the ViewModel" section:

> // - We can put an observer on the data (instead of polling for changes) and only update **the**
> //   **the** UI when the data actually changes.

**Comment by gorkhalitarang** [comment]
That is not a issue close it. Stop creating such nonsense issue.

**Comment by edwinderepuesto** [comment]
Hi @gorkhalitarang, I just wanted to point out the mistake there (I know it's small), and creating an issue here was the only way I found to communicate it ("We made a mistake?" in the codelab leads here). If you know a better way to reach out to the authors of the codelab for this please let me know.

**Comment by gorkhalitarang** [comment]
Again thats not a issue. There are real issues in the codelab and in this repo which are yet to be changed, if you understood even half of it you wouldnt create such stupid comment mistake. Take some time and learn. Best of luck there is a lot to cover.

**Comment by espertus** [comment]
@edwinderepuesto I worked at Google for 14 years and can tell you that corrections of typos are appreciated. The same is true at Mozilla, where I currently work. Thank you for contributing to improving documentation.

@gorkhalitarang I see that you are new to GitHub. Welcome! Some tips:
- Upvoting one's own comments is frowned on.
- Downvoting comments is unusual, unlike on platforms like Reddit.
- Politeness is highly valued.

**Comment by edwinderepuesto** [comment]
@espertus Wow, thank you so much for your kindness 🙏.. I really didn't want to add any more off-topic comments here, but I just don't know what would be the right way to contact you regarding what you mentioned.

**Comment by gorkhalitarang** [comment]
@espertus Wow you must be so professional. Stop giving me tips about comment what do you know about it. If you actually appreciate him about reporting typo in comments you are so great. There are lots of mistake in this codelabs try looking at that besides the the typo in comment. And I see you are very polite and you assumed everything about me looking at my github profile. Well we all work somewhere and have some level of experiences. You should see my issue and have a look at the codelabs because there mistakes which i have pointed out. Lastly why everyone comments when they are butt hurt by what other says. I dont see any comment on the issue which I created. So stop with all this nonsense.

**Comment by gorkhalitarang** [comment]
@edwinderepuesto go check the codelabs and this time try to find actual mistake except for the comments and you will find many those mistakes. Again all I was saying was there is already lots of open issues in this repo and no one replys anything useful. But they can start this huge comversation in comments. Again check the codelabs and you will find actuat mistake which i was saying this whole entire time

**Comment by espertus** [comment]
@edwinderepuesto I'll contact you via email.

**Comment by florina-muntenescu** [comment]
Looks like this was fixed meanwhile.
Thanks for reporting!
